import type { Metadata } from 'next'
import { Geologica } from 'next/font/google'
import './globals.css'

const geologica = Geologica({ 
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Alertigator - Discord Utility Bot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={geologica.className}>{children}</body>
    </html>
  )
}
